name: next_step
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  carousel_slider: ^3.0.0
  provider: ^5.0.0
  firebase_core: ^1.2.0
  firebase_auth: ^1.2.0
  cloud_firestore: ^2.2.0
  modal_progress_hud: ^0.1.3
  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assates/images/
  fonts:
    - family: OpenSansCondensed
      fonts:
        - asset: assates/fonts/OpenSansCondensed-Light.ttf
    - family: YanoneKaffeesatz
      fonts:
        - asset: assates/fonts/YanoneKaffeesatz-Light.ttf
